CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    published_year INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    borrowed_by VARCHAR(255),
    borrowed_date DATE
);
