-- Preserve existing products while moving their category names into shared rows.
CREATE TABLE skincare_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO skincare_category (name)
SELECT DISTINCT category FROM skincare_product;

ALTER TABLE skincare_product ADD COLUMN category_id BIGINT;
UPDATE skincare_product
SET category_id = (SELECT id FROM skincare_category WHERE name = skincare_product.category);
ALTER TABLE skincare_product ALTER COLUMN category_id SET NOT NULL;
ALTER TABLE skincare_product ADD CONSTRAINT fk_product_category
    FOREIGN KEY (category_id) REFERENCES skincare_category(id);
ALTER TABLE skincare_product DROP COLUMN category;
